### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TeodorKolev** [anasAsh/ngx-scroll-event#4] opened 2017-12-04 14:22 UTC
Angular 4

**Comment by anasAsh** [comment] 2017-12-04 14:25
Hello TeodorKolev, would you like to share any details? What are you trying to do, what is not working, when it is not working?

**Comment by TeodorKolev** [comment] 2017-12-04 14:27
@anasAsh Hi, there is no event called. There is no errors, but event did not trigger at all

**Comment by TeodorKolev** [comment] 2017-12-04 14:28
I have copied both files from src folder. I have added module in my app modules, I have put detect-scroll (onScroll)="handleScroll($event)" on my table component and rest of code in my table component. On scroll - no errors and no console outputs

**Comment by seanjb** [comment] 2017-12-07 10:01
Make sure you have added the detect-scroll attribute to the element you are trying to detect scrolls on

i.e. 
`<div detect-scroll (onScroll)="handleScroll($event)">.....</div>`

Worked for me

**Comment by dorival** [comment] 2017-12-11 23:09
I am experiencing the same problem, did exactly what @seanjb did, but it does not report scrolls or give any errors.

Does it support container sizes defined using Flex?

**Comment by wilsonoen** [comment] 2018-01-04 03:36
I added the detect-scroll `directive` and` (onScroll)` attribute in `<div>` tag inside a component. It gives no console log or error. Does it have to be in app level (app.component.html)?

**Comment by hazem-tamimi** [comment] 2018-01-15 10:55
I've included it to a child module and it is working fine with me. You have to make sure you are adding the directive and the event to the scrollable HTML element.

**Comment by iamisti** [comment] 2018-01-24 09:59
@hazem-tamimi I've added the directive and the event to the scrollable HTML, still doesn't work for me...

**Comment by anasAsh** [comment] 2018-02-01 13:17
@iamisti i have created a small demo to help you, please check, if the demo is working, but your code is not working, let me know what are the differences on your side.

[ngx-scroll-event-demo](https://github.com/anasAsh/ngx-scroll-event-demo)

**Comment by anasAsh** [comment] 2018-02-07 12:00
will close the issue since I can not reproduce the case and no one is providing a reproducible example.

**Closed as completed by anasAsh** 2018-02-07 12:00 UTC

**Comment by agiratech-vigneshm** [comment] 2018-03-05 10:18
happens to me with a container which is set overflow-y scroll and display:flex. I think the problem should be the directive not playing well with flex.
